version: "3.3"
services:
  # NodeJS Backend Server
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
      # The following line makes node_modules a private volume instead of synced to the folder
      - /app/node_modules/
  nginx:
    depends_on:
      - keycloak
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled:ro
      # Disable nginx html
      - /etc/nginx/
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - "./db/data:/var/lib/postgresql/data"
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak
      DB_SCHEMA: public
