version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./production.Dockerfile
    networks:
      - prodnet
    ports:
      - "3000:80"

networks:
  prodnet:
    driver: bridge
